Use numberic USER in Dockerfile for PodSecurityPolicy set to runAsNon…
cloudability/metrics-agent pull request #87
Opened 2020-09-11 12:41 UTC by sbkg0002

#### What does this PR do?
Use numberic USER in Dockerfile for PodSecurityPolicy set to `runAsNonRoot`

Tested in EKS 1.17 clusters, via both manifest and Helm deployment.

2020-09-11 12:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cloudability/metrics-agent?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cloudability/metrics-agent?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cloudability/metrics-agent?pullRequest=87) it.</sub>

2020-09-16 17:53 UTC, mnorbury requested changes
Thanks for the changes. Would you mind incrementing the version to 1.2.1 in the following file:-

https://github.com/cloudability/metrics-agent/blob/master/version/version.go#L4

2020-09-17 06:35 UTC, sbkg0002 commented
Done @mnorbury

2020-09-17 14:27 UTC, mnorbury approved these changes
This looks good to me. Thank you for making these changes.

2020-09-17 14:30 UTC, merged